# Numpy : Numerical Python
Advantages of numpy:
    1. Faster operations
    2. allow several mathematical operations

In [1]:
import numpy as np

 List vs numpy: time taken by both of them

In [2]:
from time import process_time

time taken by a list

In [8]:
py_list = [i for i in range(10000)]
start_time = process_time()
print(start_time)
py_list = [i+5 for i in py_list]
end_time = process_time()
print(end_time)
print(end_time - start_time)

1.046875
1.046875
0.0


In [9]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
print(start_time)
np_array +=5
end_time = process_time()
print(end_time)
print(end_time - start_time)

1.078125
1.078125
0.0


### Numpy arrays

In [11]:
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [12]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
# Creating a 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
a.shape

(4,)

In [15]:
# 2D array
b =np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [16]:
b.shape

(2, 4)

In [17]:
c=np.array([[1,2,3,4],[5,6,7,8]], dtype =float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


## Placeholders

In [18]:
# numpy array of 0
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# numpy array of 1
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
# create identity matrix
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# array with random values
r = np.random.random((3,4))
r

array([[0.91067546, 0.6523522 , 0.54428014, 0.38823217],
       [0.54919889, 0.68448096, 0.75995297, 0.76433681],
       [0.13226013, 0.14127833, 0.1366822 , 0.37290016]])

In [29]:
# array with random integers within a specific range
rand_int = np.random.randint(10,100,(3,5))
rand_int

array([[48, 69, 68, 44, 12],
       [59, 23, 14, 57, 53],
       [46, 55, 21, 44, 75]])

In [31]:
# array of evenly spaced values
even_space = np.linspace(10,30,6)
even_space

array([10., 14., 18., 22., 26., 30.])

In [33]:
# array of evenly spaced values with specifing step
even_step = np.arange(10,30,5)
even_step

array([10, 15, 20, 25])

In [37]:
# convert list to numpy array
list2 = [10,20,30,40,50]
np_arr = np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 30 40 50]


numpy.ndarray

## Analysing numpy array

In [38]:
c = np.random.randint(10,90,(5,5))
print(c)

[[52 43 32 79 60]
 [50 62 49 38 47]
 [87 46 69 69 55]
 [62 33 26 21 59]
 [12 76 10 31 36]]


In [39]:
# array dimension
c.shape

(5, 5)

In [40]:
# number of dimensions
c.ndim

2

In [41]:
# number of element in array
c.size

25

In [42]:
# check datatype of the values in the array
c.dtype

dtype('int32')

In [43]:
# Mathematical operations 
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 9 8]
 [2 7 3]
 [4 4 6]]
[[11 18 19]
 [13 18 11]
 [11 18 19]]


In [45]:
print(a+b)

[[14 27 27]
 [15 25 14]
 [15 22 25]]


In [46]:
print(a-b)
print(a*b)
print(a/b)

[[ -8  -9 -11]
 [-11 -11  -8]
 [ -7 -14 -13]]
[[ 33 162 152]
 [ 26 126  33]
 [ 44  72 114]]
[[0.27272727 0.5        0.42105263]
 [0.15384615 0.38888889 0.27272727]
 [0.36363636 0.22222222 0.31578947]]


In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[6 6 1]
 [7 5 6]
 [5 2 6]]
[[11 12 12]
 [18 13 13]
 [19 15 12]]


In [50]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 18 13]
 [25 18 19]
 [24 17 18]]
[[ -5  -6 -11]
 [-11  -8  -7]
 [-14 -13  -6]]
[[ 66  72  12]
 [126  65  78]
 [ 95  30  72]]
[[0.54545455 0.5        0.08333333]
 [0.38888889 0.38461538 0.46153846]
 [0.26315789 0.13333333 0.5       ]]


## Array Manipulation

### array Transpose

In [51]:

arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[1 2 0]
 [2 2 9]]
(2, 3)


In [52]:
trans = np.transpose(arr)
print(trans)
trans.shape

[[1 2]
 [2 2]
 [0 9]]


(3, 2)

In [53]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[6 9 7]
 [7 6 9]]
(2, 3)


In [54]:
trans2 = arr.T
print(trans2)
trans2.shape

[[6 7]
 [9 6]
 [7 9]]


(3, 2)

###  Reshapping the array

In [55]:
a = np.random.randint(0,10,(2,3))
print(a)
a.shape

[[8 7 9]
 [7 8 2]]


(2, 3)

In [56]:
b = a.reshape(3,2)
print(b)
b.shape

[[8 7]
 [9 7]
 [8 2]]


(3, 2)